[build]
  publish = "public"
  command = "bash build-prod.sh"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://www.pavesasrl.it"
    sitemapPath = "public/sitemap.xml"
    providers = ["google", "bing", "yandex"]